on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    
    defaults:
      run:
        shell: cmd

    steps:
    - uses: actions/checkout@v3
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Stop site
      run: appcmd stop sites "cardgamedb"
    - name: Publish Release
      run: dotnet publish CardGameDBSites\SkytearHorde.Website --configuration Release -o C:\inetpub\cardgamedb
    - name: Start site
      run: appcmd start sites "cardgamedb"
